# Generated by Django 3.2.4 on 2021-06-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('asistio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['id_cita'],
            },
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('dui', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=2000)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'ordering': ['dui'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunacion.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['id_municipio'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunacion.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id_dosis', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_dosis', models.DateTimeField()),
                ('dosis_vacunacion', models.CharField(default='primera', max_length=40)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunacion.cita')),
            ],
            options={
                'verbose_name': 'Dosis',
                'ordering': ['id_dosis'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunacion.ciudadano'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunacion.sede'),
        ),
    ]
